<?php return array (
  'site_title' => 'IsabiPay Escrow',
  'time_zone' => 'UTC',
  'currency' => 'USD',
  'currency_symbol' => '$',
  'theme' => 'darkmode',
  'fraction_number' => 2,
  'paginate' => 20,
  'strong_password' => 0,
  'registration' => 1,
  'is_active_cron_notification' => 1,
  'error_log' => 1,
  'email_verification' => 1,
  'email_notification' => 1,
  'sms_verification' => 0,
  'sms_notification' => 0,
  'tawk_id' => '62d7e2fcb0d10b6f3e7d4766',
  'tawk_status' => 1,
  'fb_messenger_status' => 0,
  'fb_app_id' => '1983831301869331',
  'fb_page_id' => '1983831301869331',
  'reCaptcha_status_login' => 0,
  'reCaptcha_status_registration' => 0,
  'MEASUREMENT_ID' => 'G-TFQZ8YZ468',
  'analytic_status' => 0,
  'minimum_escrow' => 1.0,
  'maximum_escrow' => 1000000.0,
  'escrow_charge' => 2.0,
  'sender_email' => 'hello@escrow.icu',
  'sender_email_name' => 'IsabiPay Escrow',
  'email_configuration' => 
  array (
    'name' => 'smtp',
    'smtp_host' => 'smtp-relay.brevo.com',
    'smtp_port' => '587',
    'smtp_encryption' => 'tls',
    'smtp_username' => '6cd0d5001@smtp-brevo.com',
    'smtp_password' => '0xMcOQPR4kna6h91',
  ),
  'push_notification' => 1,
  'email_description' => '"Hello [[name]] <br><br><br>\\r\\n\\r\\n [[message]]"',
);